"""add is pending_verification_jti in the user table

Revision ID: 8292c482c5c2
Revises: e64abc0807d1
Create Date: 2026-07-13 15:15:50.892167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8292c482c5c2"
down_revision: Union[str, Sequence[str], None] = "e64abc0807d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("pending_verification_jti", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "pending_verification_jti")
    # ### end Alembic commands ###
