"""adding scopes column in the users table

Revision ID: f0589143e900
Revises: ff2fd6286f38
Create Date: 2026-08-03 12:37:43.610353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0589143e900'
down_revision: Union[str, Sequence[str], None] = 'ff2fd6286f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scopes', sa.String(), nullable=False, server_default="users:read users:write"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scopes')
    # ### end Alembic commands ###
