"""add pending_password_reset_jti to users

Revision ID: ff2fd6286f38
Revises: 8292c482c5c2
Create Date: 2026-07-23 21:02:09.686991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2fd6286f38'
down_revision: Union[str, Sequence[str], None] = '8292c482c5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pending_password_reset_jti', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_password_reset_jti')
    # ### end Alembic commands ###
