services:
  devcontainer:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres-primary:5432/${DB_NAME}
      DATABASE_REPLICA_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres-replica:5432/${DB_NAME}
      REDIS_HOST: redis
      MAIL_SERVER: mailpit
    volumes:
      - .:/workspaces/fasti-kit:cached
      - devcontainer_venv:/workspaces/fasti-kit/.venv
    depends_on:
      postgres-primary:
        condition: service_healthy
      postgres-replica:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_started

volumes:
  devcontainer_venv:
