import subprocess
from pathlib import Path

import typer
from rich.console import Console
from rich.prompt import Prompt

from scripts._boilerplate import to_pascal_case, to_snake_case
from scripts.create_factory import create_factory

console = Console()


def _required_imports(domain: str, snake: str, pascal: str) -> list[str]:
    return [
        "import uuid",
        f"from {domain}.repositories.{snake}_repository import {pascal}Repository",
        f"from {domain}.services.{snake}_service import {pascal}Service",
        f"from core.factories.{snake}_factory import (\n"
        f"    Create{pascal}RequestFactory,\n"
        f"    Update{pascal}RequestFactory,\n"
        f")",
    ]


def _test_marker(snake: str) -> str:
    return f"async def test_{snake}_repository_add_and_get"


def _render_block(domain: str, snake: str, pascal: str) -> str:
    return f"""# ---------------------------------------------------------------------------
# {pascal} ({snake}) - generated by `uv run create-test --domain {domain} --name {snake}`
# ---------------------------------------------------------------------------


async def test_{snake}_repository_add_and_get(db) -> None:
    \"\"\"add() persists a {snake}; get() retrieves it by id.\"\"\"
    repo = {pascal}Repository(db)
    data = Create{pascal}RequestFactory.build()

    record = await repo.add(**data.model_dump())
    assert record.id is not None
    assert record.is_active is True

    fetched = await repo.get(record.id)
    assert fetched is not None
    assert fetched.id == record.id


async def test_{snake}_repository_get_returns_none_for_missing(db) -> None:
    \"\"\"get() with an unknown UUID returns None without raising.\"\"\"
    repo = {pascal}Repository(db)
    assert await repo.get(uuid.uuid4()) is None


async def test_{snake}_repository_update(db) -> None:
    \"\"\"update() applies fields to an existing {snake}.\"\"\"
    repo = {pascal}Repository(db)
    created = await repo.add(**Create{pascal}RequestFactory.build().model_dump())

    updated = await repo.update(
        created.id, **Update{pascal}RequestFactory.build().model_dump()
    )
    assert updated is not None
    assert updated.id == created.id


async def test_{snake}_repository_soft_delete(db) -> None:
    \"\"\"delete() marks the {snake} inactive rather than removing the row.\"\"\"
    repo = {pascal}Repository(db)
    created = await repo.add(**Create{pascal}RequestFactory.build().model_dump())

    deleted = await repo.delete(created.id)
    assert deleted is not None
    assert deleted.is_active is False

    still_there = await repo.get(created.id)
    assert still_there is not None
    assert still_there.is_active is False


async def test_{snake}_repository_force_delete(db) -> None:
    \"\"\"force_delete() removes the row entirely.\"\"\"
    repo = {pascal}Repository(db)
    created = await repo.add(**Create{pascal}RequestFactory.build().model_dump())

    await repo.force_delete(created.id)
    assert await repo.get(created.id) is None


async def test_{snake}_service_create(db) -> None:
    \"\"\"create() delegates to the repository and returns an entity.\"\"\"
    service = {pascal}Service({pascal}Repository(db))
    record = await service.create(Create{pascal}RequestFactory.build())
    assert record.id is not None


async def test_{snake}_service_get_returns_none_for_missing(db) -> None:
    service = {pascal}Service({pascal}Repository(db))
    assert await service.get(uuid.uuid4()) is None


async def test_{snake}_service_update(db) -> None:
    repo = {pascal}Repository(db)
    service = {pascal}Service(repo)
    created = await service.create(Create{pascal}RequestFactory.build())

    updated = await service.update(created.id, Update{pascal}RequestFactory.build())
    assert updated is not None
    assert updated.id == created.id


async def test_{snake}_service_delete_soft(db) -> None:
    repo = {pascal}Repository(db)
    service = {pascal}Service(repo)
    created = await service.create(Create{pascal}RequestFactory.build())

    deleted = await service.delete(created.id)
    assert deleted is not None
    assert deleted.is_active is False


async def test_{snake}_service_force_delete(db) -> None:
    repo = {pascal}Repository(db)
    service = {pascal}Service(repo)
    created = await service.create(Create{pascal}RequestFactory.build())

    assert await service.delete(created.id, force=True) is not None
    assert await repo.get(created.id) is None
"""


def _new_file_content(domain: str, imports: list[str], block: str) -> str:
    domain_pascal = to_pascal_case(domain)
    header = f'''"""
Integration tests for the {domain_pascal} domain: repository and service layers.

These tests run inside the transactional db fixture (savepoint rollback),
so all writes are automatically discarded after each test.
"""

'''
    return header + "\n".join(imports) + "\n\n\n" + block


def _merge_into_existing(content: str, imports: list[str]) -> str:
    lines = content.splitlines()
    last_import_idx = -1
    for idx, line in enumerate(lines):
        if line.startswith(("import ", "from ")):
            last_import_idx = idx

    missing = [line for line in imports if line not in content]
    if not missing or last_import_idx == -1:
        return content

    insert_at = last_import_idx + 1
    new_lines = lines[:insert_at] + missing + lines[insert_at:]
    return "\n".join(new_lines) + "\n"


def create_test(
    domain: str = typer.Option(None, "--domain", "-d", help="Target domain folder"),
    name: str = typer.Option(None, "--name", "-n", help="Entity/Test name"),
) -> None:
    """Scaffold repository/service tests for a domain feature using its factory."""

    # 1. Interactive Prompts
    if not domain:
        domain = Prompt.ask(
            "[bold blue]Enter domain name[/bold blue] (e.g., inventory)"
        )
    if not name:
        name = Prompt.ask("[bold blue]Enter test name[/bold blue] (e.g., product)")

    # 2. Setup Variables
    snake = to_snake_case(name)
    pascal = to_pascal_case(name)

    # 3. Ensure the Create/Update request factories exist first
    create_factory(domain=domain, name=name)

    # 4. Write/merge the test file
    test_path = Path("tests") / f"test_{to_snake_case(domain)}_domain.py"
    imports = _required_imports(domain, snake, pascal)
    block = _render_block(domain, snake, pascal)

    if test_path.exists():
        content = test_path.read_text()
        if _test_marker(snake) in content:
            console.print(f"skip: tests for {name} already exist in {test_path}")
            return
        content = _merge_into_existing(content, imports)
        content = content.rstrip("\n") + "\n\n\n" + block
    else:
        test_path.parent.mkdir(parents=True, exist_ok=True)
        content = _new_file_content(domain, imports, block)

    test_path.write_text(content)
    console.print(
        f"[bold green]✨ Wrote tests for {pascal} to {test_path}[/bold green]"
    )

    # 5. Best-effort: run the generated tests immediately
    try:
        result = subprocess.run(  # noqa: S603
            ["uv", "run", "pytest", str(test_path), "-v"],  # noqa: S607
            check=False,
            capture_output=True,
            text=True,
            timeout=120,
        )
        console.print(result.stdout[-4000:])
        if result.returncode != 0:
            console.print(result.stderr[-2000:])
            console.print(
                "[yellow]Generated tests did not pass — check the output above.[/yellow]"
            )
        else:
            console.print("[bold green]Generated tests passed.[/bold green]")
    except (OSError, subprocess.TimeoutExpired) as exc:
        console.print(
            f"[yellow]Could not auto-run pytest ({exc}). Bring up the test DB with "
            f"'docker compose up -d postgres-primary postgres-replica' and run "
            f"'uv run pytest {test_path}' yourself.[/yellow]"
        )


def main() -> None:
    typer.run(create_test)


if __name__ == "__main__":
    main()
